name: Prettier code formatter (Disabled for personal portfolio)
on:
  workflow_dispatch:
jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Prettier check disabled for personal portfolio"
